// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-R0I225JxiySnGaHhFOkgZABqn6fXYDE',
    appId: '1:433723340637:web:b6ffff388de04d9beb1ab4',
    messagingSenderId: '433723340637',
    projectId: 'puerta-app-7a930',
    authDomain: 'puerta-app-7a930.firebaseapp.com',
    databaseURL: 'https://puerta-app-7a930-default-rtdb.firebaseio.com',
    storageBucket: 'puerta-app-7a930.firebasestorage.app',
    measurementId: 'G-2C21P48WX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZvChupgamvPbnB-eLpSldr75S38ZSc3I',
    appId: '1:433723340637:android:4ee797f6cf619213eb1ab4',
    messagingSenderId: '433723340637',
    projectId: 'puerta-app-7a930',
    databaseURL: 'https://puerta-app-7a930-default-rtdb.firebaseio.com',
    storageBucket: 'puerta-app-7a930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYpQKaOaKDwn-Oqlv7l_51vVo9DY-euvY',
    appId: '1:433723340637:ios:e0b70638481cc926eb1ab4',
    messagingSenderId: '433723340637',
    projectId: 'puerta-app-7a930',
    databaseURL: 'https://puerta-app-7a930-default-rtdb.firebaseio.com',
    storageBucket: 'puerta-app-7a930.firebasestorage.app',
    iosBundleId: 'com.example.focoLedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYpQKaOaKDwn-Oqlv7l_51vVo9DY-euvY',
    appId: '1:433723340637:ios:e0b70638481cc926eb1ab4',
    messagingSenderId: '433723340637',
    projectId: 'puerta-app-7a930',
    databaseURL: 'https://puerta-app-7a930-default-rtdb.firebaseio.com',
    storageBucket: 'puerta-app-7a930.firebasestorage.app',
    iosBundleId: 'com.example.focoLedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-R0I225JxiySnGaHhFOkgZABqn6fXYDE',
    appId: '1:433723340637:web:b994499803817fd9eb1ab4',
    messagingSenderId: '433723340637',
    projectId: 'puerta-app-7a930',
    authDomain: 'puerta-app-7a930.firebaseapp.com',
    databaseURL: 'https://puerta-app-7a930-default-rtdb.firebaseio.com',
    storageBucket: 'puerta-app-7a930.firebasestorage.app',
    measurementId: 'G-YTYR1066YW',
  );
}
